# Generated by Django 2.1.5 on 2019-02-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20190214_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
